# Generated by Django 3.0.6 on 2020-08-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0015_merge_20200614_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_government_area', models.CharField(db_column='LGA', max_length=25)),
                ('address_or_nearest_landmark', models.CharField(help_text='By landmark we mean somewhere notable such as bustop, market, hotel, hospital etc.', max_length=50, verbose_name='address and/or nearest landmark')),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('imagefile', models.FileField(blank=True, null=True, upload_to='images/', verbose_name='upload an image')),
                ('accident_location', models.ManyToManyField(blank=True, to='usersapp.State')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
