# Generated by Django 3.0.6 on 2020-08-22 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0016_post_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='accident_location',
        ),
        migrations.AddField(
            model_name='post',
            name='accident_location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='usersapp.State'),
            preserve_default=False,
        ),
    ]
