# Generated by Django 3.0.6 on 2020-08-22 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0017_auto_20200822_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='name',
            new_name='statename',
        ),
    ]
